/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xavmovies.view;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.SpinnerNumberModel;
import xavmovies.model.dao.UpdateModel;
import xavmovies.model.dao.SelectModel;
import xavmovies.model.Filme;
import xavmovies.model.Sessao;
import xavmovies.util.Conexao;

/**
 *
 * @author 205182030
 */
public class CompraIngresso extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDeFilme
     */
    private Object duracao;

    public CompraIngresso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        List<String> sessoes = new ArrayList<>();
        List<Sessao> retornobd = SelectModel.verifySessionAll();

        sessoes.add(" ");
        for (Sessao sessao : retornobd) {
            sessoes.add("Filme: " + sessao.getFilme() + ", as " + sessao.getHorario() + " horas, na sala: " + sessao.getSala());
        }
        campoSessao = new javax.swing.JComboBox<>();
        botaoCadastrar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        qntdIngresso = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        ingressosDisponiveis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Compra de Ingresso");

        jLabel2.setText("Sessao:");

        campoSessao.setModel(new javax.swing.DefaultComboBoxModel(sessoes.toArray()));
        campoSessao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                campoSessaoItemStateChanged(evt);
            }
        });
        campoSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSessaoActionPerformed(evt);
            }
        });

        botaoCadastrar.setText("Comprar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Cancelar");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantidade de Ingressos:");

        qntdIngresso.setModel(new SpinnerNumberModel(1, 0, 5, 1));

        jLabel6.setText("ingressos");

        ingressosDisponiveis.setText("disponiveis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(campoSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botaoCadastrar)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(qntdIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)
                                        .addGap(143, 143, 143)
                                        .addComponent(ingressosDisponiveis)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoExcluir)))))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(qntdIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ingressosDisponiveis))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrar)
                    .addComponent(botaoExcluir))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        JComponent editor = qntdIngresso.getEditor();
        ( (DefaultEditor)editor).getTextField().setFocusable( false ); // Converte para DefaultEditor e acessa o TextField

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSessaoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_campoSessaoActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // TODO add your handling code here
        String valorSelecionado = campoSessao.getSelectedItem().toString();

        String valorFormatado[] = valorSelecionado.split(" ");
        int numeroIdentificacao = Integer.parseInt(valorFormatado[valorFormatado.length - 1]);
        String horario = valorFormatado[valorFormatado.length - 5];
        String filme = valorFormatado[1];

        if (UpdateModel.vendaIngresso(numeroIdentificacao, horario, filme.replace(",", ""), Integer.parseInt(qntdIngresso.getValue().toString()))) {
            this.dispose();
        }

    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void campoSessaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_campoSessaoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            try {
                String valorSelecionado = evt.getItem().toString();
                String valorFormatado[] = valorSelecionado.split(" ");
                int numeroIdentificacao = Integer.parseInt(valorFormatado[valorFormatado.length - 1]);
                String horario = valorFormatado[valorFormatado.length - 5];
                String filme = valorFormatado[1];
                String disponiveis = SelectModel.verifyAvailableIngresso(numeroIdentificacao, horario, filme.replace(",", ""));

                ingressosDisponiveis.setText(disponiveis + " disponiveis");
                try {
                    qntdIngresso.setModel(new SpinnerNumberModel(1, 0, Integer.parseInt(disponiveis), 1));
                } catch (java.lang.IllegalArgumentException e) {
                    
                    qntdIngresso.setModel(new SpinnerNumberModel(0, 0, 0, 1));
                    ingressosDisponiveis.setText(disponiveis + " disponivel");
                }

            } catch (java.lang.ArrayIndexOutOfBoundsException a) {

            }
        }
    }//GEN-LAST:event_campoSessaoItemStateChanged

    private void campoDuracaoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JComboBox<String> campoSessao;
    private javax.swing.JLabel ingressosDisponiveis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner qntdIngresso;
    // End of variables declaration//GEN-END:variables

}
